- hosts: webserver
  become: true
  tasks:

        - name: copying one file to onether
          tags: copy harsha to folder vardhan
          copy:
                  src: file
                  dest: /var/www/harsha.file
                  owner: root
                  group: root
                  mode: 0644

